skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_69_0
  CL: /Zc:threadSafeInit-

cache:
  - thirdparty.cached -> appveyor.install.bat
  - thirdparty\bin -> appveyor.install.bat
  - thirdparty\include -> appveyor.install.bat
  - thirdparty\lib -> appveyor.install.bat
  - thirdparty\share -> appveyor.install.bat
  - C:\Libraries\boost_1_69_0\stage -> appveyor.install.bat

init:
  - git --version
  - cmake --version
  - git config --global core.autocrlf true

install:
  - .\appveyor.install.bat

build_script:
  - .\build.bat test

after_build:
  - 7z a rime.zip dist thirdparty\bin thirdparty\share
  - dir dist /s

before_test:
  - copy /y dist\lib\rime.dll build\test

test_script:
  - cd build\test
  - .\Release\rime_test.exe

artifacts:
  - path: rime.zip
    name: Distributables, including binaries and OpenCC data
